# Generated by Django 2.2.4 on 2020-05-11 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pages',
        ),
    ]
