# Generated by Django 2.2.4 on 2020-05-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtors', '0003_realtor_des1'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='is_mvp',
            field=models.BooleanField(default=False),
        ),
    ]
