# Generated by Django 2.2.4 on 2020-05-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Realtors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='desc',
        ),
    ]
