# Generated by Django 2.2.4 on 2020-05-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtors', '0002_remove_realtor_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='des1',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
