# Generated by Django 2.2.4 on 2020-05-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Realtors', '0004_realtor_is_mvp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtor',
            options={'ordering': ['-contact_date']},
        ),
    ]
